// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/v2/bson"

	mock "github.com/stretchr/testify/mock"

	models "github.com/anuragthepathak/subscription-management/internal/domain/models"

	time "time"
)

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// CountActiveSubscriptions provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionRepository) CountActiveSubscriptions(_a0 context.Context, _a1 time.Time) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveSubscriptions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_CountActiveSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveSubscriptions'
type MockSubscriptionRepository_CountActiveSubscriptions_Call struct {
	*mock.Call
}

// CountActiveSubscriptions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 time.Time
func (_e *MockSubscriptionRepository_Expecter) CountActiveSubscriptions(_a0 interface{}, _a1 interface{}) *MockSubscriptionRepository_CountActiveSubscriptions_Call {
	return &MockSubscriptionRepository_CountActiveSubscriptions_Call{Call: _e.mock.On("CountActiveSubscriptions", _a0, _a1)}
}

func (_c *MockSubscriptionRepository_CountActiveSubscriptions_Call) Run(run func(_a0 context.Context, _a1 time.Time)) *MockSubscriptionRepository_CountActiveSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionRepository_CountActiveSubscriptions_Call) Return(_a0 int64, _a1 error) *MockSubscriptionRepository_CountActiveSubscriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_CountActiveSubscriptions_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockSubscriptionRepository_CountActiveSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionRepository) Create(_a0 context.Context, _a1 *models.Subscription) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Subscription) (*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Subscription) *models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Subscription) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.Subscription
func (_e *MockSubscriptionRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *MockSubscriptionRepository_Create_Call {
	return &MockSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *MockSubscriptionRepository_Create_Call) Run(run func(_a0 context.Context, _a1 *models.Subscription)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Subscription) (*models.Subscription, error)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionRepository) Delete(ctx context.Context, id bson.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockSubscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSubscriptionRepository_Delete_Call {
	return &MockSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) Return(_a0 error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) RunAndReturn(run func(context.Context, bson.ObjectID) error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveSubscriptions provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionRepository) GetActiveSubscriptions(_a0 context.Context, _a1 time.Time) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSubscriptions")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetActiveSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSubscriptions'
type MockSubscriptionRepository_GetActiveSubscriptions_Call struct {
	*mock.Call
}

// GetActiveSubscriptions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 time.Time
func (_e *MockSubscriptionRepository_Expecter) GetActiveSubscriptions(_a0 interface{}, _a1 interface{}) *MockSubscriptionRepository_GetActiveSubscriptions_Call {
	return &MockSubscriptionRepository_GetActiveSubscriptions_Call{Call: _e.mock.On("GetActiveSubscriptions", _a0, _a1)}
}

func (_c *MockSubscriptionRepository_GetActiveSubscriptions_Call) Run(run func(_a0 context.Context, _a1 time.Time)) *MockSubscriptionRepository_GetActiveSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetActiveSubscriptions_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionRepository_GetActiveSubscriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetActiveSubscriptions_Call) RunAndReturn(run func(context.Context, time.Time) ([]*models.Subscription, error)) *MockSubscriptionRepository_GetActiveSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: _a0
func (_m *MockSubscriptionRepository) GetAll(_a0 context.Context) ([]*models.Subscription, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Subscription, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Subscription); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSubscriptionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockSubscriptionRepository_Expecter) GetAll(_a0 interface{}) *MockSubscriptionRepository_GetAll_Call {
	return &MockSubscriptionRepository_GetAll_Call{Call: _e.mock.On("GetAll", _a0)}
}

func (_c *MockSubscriptionRepository_GetAll_Call) Run(run func(_a0 context.Context)) *MockSubscriptionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetAll_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*models.Subscription, error)) *MockSubscriptionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionRepository) GetByID(_a0 context.Context, _a1 bson.ObjectID) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockSubscriptionRepository_Expecter) GetByID(_a0 interface{}, _a1 interface{}) *MockSubscriptionRepository_GetByID_Call {
	return &MockSubscriptionRepository_GetByID_Call{Call: _e.mock.On("GetByID", _a0, _a1)}
}

func (_c *MockSubscriptionRepository_GetByID_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*models.Subscription, error)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionRepository) GetByUserID(_a0 context.Context, _a1 bson.ObjectID) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) []*models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockSubscriptionRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockSubscriptionRepository_Expecter) GetByUserID(_a0 interface{}, _a1 interface{}) *MockSubscriptionRepository_GetByUserID_Call {
	return &MockSubscriptionRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", _a0, _a1)}
}

func (_c *MockSubscriptionRepository_GetByUserID_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockSubscriptionRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByUserID_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, bson.ObjectID) ([]*models.Subscription, error)) *MockSubscriptionRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCanceledExpiredSubscriptions provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionRepository) GetCanceledExpiredSubscriptions(_a0 context.Context, _a1 time.Time) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCanceledExpiredSubscriptions")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCanceledExpiredSubscriptions'
type MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call struct {
	*mock.Call
}

// GetCanceledExpiredSubscriptions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 time.Time
func (_e *MockSubscriptionRepository_Expecter) GetCanceledExpiredSubscriptions(_a0 interface{}, _a1 interface{}) *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call {
	return &MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call{Call: _e.mock.On("GetCanceledExpiredSubscriptions", _a0, _a1)}
}

func (_c *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call) Run(run func(_a0 context.Context, _a1 time.Time)) *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call) RunAndReturn(run func(context.Context, time.Time) ([]*models.Subscription, error)) *MockSubscriptionRepository_GetCanceledExpiredSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsDueForReminder provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionRepository) GetSubscriptionsDueForReminder(_a0 context.Context, _a1 []int, _a2 time.Time) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsDueForReminder")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int, time.Time) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int, time.Time) []*models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsDueForReminder'
type MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call struct {
	*mock.Call
}

// GetSubscriptionsDueForReminder is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []int
//   - _a2 time.Time
func (_e *MockSubscriptionRepository_Expecter) GetSubscriptionsDueForReminder(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call {
	return &MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call{Call: _e.mock.On("GetSubscriptionsDueForReminder", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call) Run(run func(_a0 context.Context, _a1 []int, _a2 time.Time)) *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call) RunAndReturn(run func(context.Context, []int, time.Time) ([]*models.Subscription, error)) *MockSubscriptionRepository_GetSubscriptionsDueForReminder_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsDueForRenewal provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionRepository) GetSubscriptionsDueForRenewal(_a0 context.Context, _a1 time.Time, _a2 time.Time) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsDueForRenewal")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []*models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsDueForRenewal'
type MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call struct {
	*mock.Call
}

// GetSubscriptionsDueForRenewal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 time.Time
//   - _a2 time.Time
func (_e *MockSubscriptionRepository_Expecter) GetSubscriptionsDueForRenewal(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call {
	return &MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call{Call: _e.mock.On("GetSubscriptionsDueForRenewal", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call) Run(run func(_a0 context.Context, _a1 time.Time, _a2 time.Time)) *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) ([]*models.Subscription, error)) *MockSubscriptionRepository_GetSubscriptionsDueForRenewal_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, subscription
func (_m *MockSubscriptionRepository) Update(ctx context.Context, subscription *models.Subscription) (*models.Subscription, error) {
	ret := _m.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Subscription) (*models.Subscription, error)); ok {
		return rf(ctx, subscription)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Subscription) *models.Subscription); ok {
		r0 = rf(ctx, subscription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Subscription) error); ok {
		r1 = rf(ctx, subscription)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - subscription *models.Subscription
func (_e *MockSubscriptionRepository_Expecter) Update(ctx interface{}, subscription interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", ctx, subscription)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(ctx context.Context, subscription *models.Subscription)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Subscription) (*models.Subscription, error)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
