// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/v2/bson"

	mock "github.com/stretchr/testify/mock"

	models "github.com/anuragthepathak/subscription-management/internal/domain/models"
)

// MockBillRepository is an autogenerated mock type for the BillRepository type
type MockBillRepository struct {
	mock.Mock
}

type MockBillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillRepository) EXPECT() *MockBillRepository_Expecter {
	return &MockBillRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *MockBillRepository) Create(_a0 context.Context, _a1 *models.Bill) (*models.Bill, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Bill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Bill) (*models.Bill, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Bill) *models.Bill); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Bill) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBillRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.Bill
func (_e *MockBillRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *MockBillRepository_Create_Call {
	return &MockBillRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *MockBillRepository_Create_Call) Run(run func(_a0 context.Context, _a1 *models.Bill)) *MockBillRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Bill))
	})
	return _c
}

func (_c *MockBillRepository_Create_Call) Return(_a0 *models.Bill, _a1 error) *MockBillRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Bill) (*models.Bill, error)) *MockBillRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: _a0, _a1
func (_m *MockBillRepository) GetByID(_a0 context.Context, _a1 bson.ObjectID) (*models.Bill, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Bill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*models.Bill, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *models.Bill); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBillRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockBillRepository_Expecter) GetByID(_a0 interface{}, _a1 interface{}) *MockBillRepository_GetByID_Call {
	return &MockBillRepository_GetByID_Call{Call: _e.mock.On("GetByID", _a0, _a1)}
}

func (_c *MockBillRepository_GetByID_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockBillRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockBillRepository_GetByID_Call) Return(_a0 *models.Bill, _a1 error) *MockBillRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_GetByID_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*models.Bill, error)) *MockBillRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentBill provides a mock function with given fields: _a0, _a1
func (_m *MockBillRepository) GetRecentBill(_a0 context.Context, _a1 bson.ObjectID) (*models.Bill, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentBill")
	}

	var r0 *models.Bill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*models.Bill, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *models.Bill); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_GetRecentBill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentBill'
type MockBillRepository_GetRecentBill_Call struct {
	*mock.Call
}

// GetRecentBill is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockBillRepository_Expecter) GetRecentBill(_a0 interface{}, _a1 interface{}) *MockBillRepository_GetRecentBill_Call {
	return &MockBillRepository_GetRecentBill_Call{Call: _e.mock.On("GetRecentBill", _a0, _a1)}
}

func (_c *MockBillRepository_GetRecentBill_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockBillRepository_GetRecentBill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockBillRepository_GetRecentBill_Call) Return(_a0 *models.Bill, _a1 error) *MockBillRepository_GetRecentBill_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_GetRecentBill_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*models.Bill, error)) *MockBillRepository_GetRecentBill_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockBillRepository) Update(_a0 context.Context, _a1 *models.Bill) (*models.Bill, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Bill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Bill) (*models.Bill, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Bill) *models.Bill); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Bill) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBillRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.Bill
func (_e *MockBillRepository_Expecter) Update(_a0 interface{}, _a1 interface{}) *MockBillRepository_Update_Call {
	return &MockBillRepository_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *MockBillRepository_Update_Call) Run(run func(_a0 context.Context, _a1 *models.Bill)) *MockBillRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Bill))
	})
	return _c
}

func (_c *MockBillRepository_Update_Call) Return(_a0 *models.Bill, _a1 error) *MockBillRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Bill) (*models.Bill, error)) *MockBillRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillRepository creates a new instance of MockBillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillRepository {
	mock := &MockBillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
