// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/v2/bson"

	mock "github.com/stretchr/testify/mock"

	models "github.com/anuragthepathak/subscription-management/internal/domain/models"
)

// MockUserServiceInternal is an autogenerated mock type for the UserServiceInternal type
type MockUserServiceInternal struct {
	mock.Mock
}

type MockUserServiceInternal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInternal) EXPECT() *MockUserServiceInternal_Expecter {
	return &MockUserServiceInternal_Expecter{mock: &_m.Mock}
}

// FetchUserByEmailInternal provides a mock function with given fields: _a0, _a1
func (_m *MockUserServiceInternal) FetchUserByEmailInternal(_a0 context.Context, _a1 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserByEmailInternal")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInternal_FetchUserByEmailInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserByEmailInternal'
type MockUserServiceInternal_FetchUserByEmailInternal_Call struct {
	*mock.Call
}

// FetchUserByEmailInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockUserServiceInternal_Expecter) FetchUserByEmailInternal(_a0 interface{}, _a1 interface{}) *MockUserServiceInternal_FetchUserByEmailInternal_Call {
	return &MockUserServiceInternal_FetchUserByEmailInternal_Call{Call: _e.mock.On("FetchUserByEmailInternal", _a0, _a1)}
}

func (_c *MockUserServiceInternal_FetchUserByEmailInternal_Call) Run(run func(_a0 context.Context, _a1 string)) *MockUserServiceInternal_FetchUserByEmailInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserServiceInternal_FetchUserByEmailInternal_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInternal_FetchUserByEmailInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInternal_FetchUserByEmailInternal_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserServiceInternal_FetchUserByEmailInternal_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserByIDInternal provides a mock function with given fields: _a0, _a1
func (_m *MockUserServiceInternal) FetchUserByIDInternal(_a0 context.Context, _a1 bson.ObjectID) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserByIDInternal")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceInternal_FetchUserByIDInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserByIDInternal'
type MockUserServiceInternal_FetchUserByIDInternal_Call struct {
	*mock.Call
}

// FetchUserByIDInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockUserServiceInternal_Expecter) FetchUserByIDInternal(_a0 interface{}, _a1 interface{}) *MockUserServiceInternal_FetchUserByIDInternal_Call {
	return &MockUserServiceInternal_FetchUserByIDInternal_Call{Call: _e.mock.On("FetchUserByIDInternal", _a0, _a1)}
}

func (_c *MockUserServiceInternal_FetchUserByIDInternal_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockUserServiceInternal_FetchUserByIDInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockUserServiceInternal_FetchUserByIDInternal_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceInternal_FetchUserByIDInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceInternal_FetchUserByIDInternal_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*models.User, error)) *MockUserServiceInternal_FetchUserByIDInternal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceInternal creates a new instance of MockUserServiceInternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInternal {
	mock := &MockUserServiceInternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
