// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSubscriptionMetrics is an autogenerated mock type for the SubscriptionMetrics type
type MockSubscriptionMetrics struct {
	mock.Mock
}

type MockSubscriptionMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionMetrics) EXPECT() *MockSubscriptionMetrics_Expecter {
	return &MockSubscriptionMetrics_Expecter{mock: &_m.Mock}
}

// IncSubscriptionsCanceled provides a mock function with given fields: ctx
func (_m *MockSubscriptionMetrics) IncSubscriptionsCanceled(ctx context.Context) {
	_m.Called(ctx)
}

// MockSubscriptionMetrics_IncSubscriptionsCanceled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncSubscriptionsCanceled'
type MockSubscriptionMetrics_IncSubscriptionsCanceled_Call struct {
	*mock.Call
}

// IncSubscriptionsCanceled is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSubscriptionMetrics_Expecter) IncSubscriptionsCanceled(ctx interface{}) *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call {
	return &MockSubscriptionMetrics_IncSubscriptionsCanceled_Call{Call: _e.mock.On("IncSubscriptionsCanceled", ctx)}
}

func (_c *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call) Run(run func(ctx context.Context)) *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call) Return() *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call) RunAndReturn(run func(context.Context)) *MockSubscriptionMetrics_IncSubscriptionsCanceled_Call {
	_c.Run(run)
	return _c
}

// IncSubscriptionsCreated provides a mock function with given fields: ctx
func (_m *MockSubscriptionMetrics) IncSubscriptionsCreated(ctx context.Context) {
	_m.Called(ctx)
}

// MockSubscriptionMetrics_IncSubscriptionsCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncSubscriptionsCreated'
type MockSubscriptionMetrics_IncSubscriptionsCreated_Call struct {
	*mock.Call
}

// IncSubscriptionsCreated is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSubscriptionMetrics_Expecter) IncSubscriptionsCreated(ctx interface{}) *MockSubscriptionMetrics_IncSubscriptionsCreated_Call {
	return &MockSubscriptionMetrics_IncSubscriptionsCreated_Call{Call: _e.mock.On("IncSubscriptionsCreated", ctx)}
}

func (_c *MockSubscriptionMetrics_IncSubscriptionsCreated_Call) Run(run func(ctx context.Context)) *MockSubscriptionMetrics_IncSubscriptionsCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubscriptionMetrics_IncSubscriptionsCreated_Call) Return() *MockSubscriptionMetrics_IncSubscriptionsCreated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriptionMetrics_IncSubscriptionsCreated_Call) RunAndReturn(run func(context.Context)) *MockSubscriptionMetrics_IncSubscriptionsCreated_Call {
	_c.Run(run)
	return _c
}

// NewMockSubscriptionMetrics creates a new instance of MockSubscriptionMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionMetrics {
	mock := &MockSubscriptionMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
