// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/anuragthepathak/subscription-management/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserServiceExternal is an autogenerated mock type for the UserServiceExternal type
type MockUserServiceExternal struct {
	mock.Mock
}

type MockUserServiceExternal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceExternal) EXPECT() *MockUserServiceExternal_Expecter {
	return &MockUserServiceExternal_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *MockUserServiceExternal) CreateUser(_a0 context.Context, _a1 *models.User) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceExternal_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserServiceExternal_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.User
func (_e *MockUserServiceExternal_Expecter) CreateUser(_a0 interface{}, _a1 interface{}) *MockUserServiceExternal_CreateUser_Call {
	return &MockUserServiceExternal_CreateUser_Call{Call: _e.mock.On("CreateUser", _a0, _a1)}
}

func (_c *MockUserServiceExternal_CreateUser_Call) Run(run func(_a0 context.Context, _a1 *models.User)) *MockUserServiceExternal_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserServiceExternal_CreateUser_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceExternal_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceExternal_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) (*models.User, error)) *MockUserServiceExternal_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServiceExternal) DeleteUser(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceExternal_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserServiceExternal_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockUserServiceExternal_Expecter) DeleteUser(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServiceExternal_DeleteUser_Call {
	return &MockUserServiceExternal_DeleteUser_Call{Call: _e.mock.On("DeleteUser", _a0, _a1, _a2)}
}

func (_c *MockUserServiceExternal_DeleteUser_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockUserServiceExternal_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserServiceExternal_DeleteUser_Call) Return(_a0 error) *MockUserServiceExternal_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceExternal_DeleteUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserServiceExternal_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: _a0
func (_m *MockUserServiceExternal) GetAllUsers(_a0 context.Context) ([]*models.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceExternal_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserServiceExternal_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockUserServiceExternal_Expecter) GetAllUsers(_a0 interface{}) *MockUserServiceExternal_GetAllUsers_Call {
	return &MockUserServiceExternal_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", _a0)}
}

func (_c *MockUserServiceExternal_GetAllUsers_Call) Run(run func(_a0 context.Context)) *MockUserServiceExternal_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserServiceExternal_GetAllUsers_Call) Return(_a0 []*models.User, _a1 error) *MockUserServiceExternal_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceExternal_GetAllUsers_Call) RunAndReturn(run func(context.Context) ([]*models.User, error)) *MockUserServiceExternal_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServiceExternal) GetUserByID(_a0 context.Context, _a1 string, _a2 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceExternal_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserServiceExternal_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockUserServiceExternal_Expecter) GetUserByID(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServiceExternal_GetUserByID_Call {
	return &MockUserServiceExternal_GetUserByID_Call{Call: _e.mock.On("GetUserByID", _a0, _a1, _a2)}
}

func (_c *MockUserServiceExternal_GetUserByID_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockUserServiceExternal_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserServiceExternal_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceExternal_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceExternal_GetUserByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.User, error)) *MockUserServiceExternal_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockUserServiceExternal) UpdateUser(_a0 context.Context, _a1 string, _a2 *models.UserUpdateRequest, _a3 string) (*models.User, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UserUpdateRequest, string) (*models.User, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UserUpdateRequest, string) *models.User); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.UserUpdateRequest, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceExternal_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserServiceExternal_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 *models.UserUpdateRequest
//   - _a3 string
func (_e *MockUserServiceExternal_Expecter) UpdateUser(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockUserServiceExternal_UpdateUser_Call {
	return &MockUserServiceExternal_UpdateUser_Call{Call: _e.mock.On("UpdateUser", _a0, _a1, _a2, _a3)}
}

func (_c *MockUserServiceExternal_UpdateUser_Call) Run(run func(_a0 context.Context, _a1 string, _a2 *models.UserUpdateRequest, _a3 string)) *MockUserServiceExternal_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.UserUpdateRequest), args[3].(string))
	})
	return _c
}

func (_c *MockUserServiceExternal_UpdateUser_Call) Return(_a0 *models.User, _a1 error) *MockUserServiceExternal_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceExternal_UpdateUser_Call) RunAndReturn(run func(context.Context, string, *models.UserUpdateRequest, string) (*models.User, error)) *MockUserServiceExternal_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceExternal creates a new instance of MockUserServiceExternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceExternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceExternal {
	mock := &MockUserServiceExternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
