// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/v2/bson"

	mock "github.com/stretchr/testify/mock"

	models "github.com/anuragthepathak/subscription-management/internal/domain/models"

	time "time"
)

// MockSubscriptionServiceInternal is an autogenerated mock type for the SubscriptionServiceInternal type
type MockSubscriptionServiceInternal struct {
	mock.Mock
}

type MockSubscriptionServiceInternal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionServiceInternal) EXPECT() *MockSubscriptionServiceInternal_Expecter {
	return &MockSubscriptionServiceInternal_Expecter{mock: &_m.Mock}
}

// FetchCanceledExpiredSubscriptionsInternal provides a mock function with given fields: _a0
func (_m *MockSubscriptionServiceInternal) FetchCanceledExpiredSubscriptionsInternal(_a0 context.Context) ([]*models.Subscription, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for FetchCanceledExpiredSubscriptionsInternal")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Subscription, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Subscription); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCanceledExpiredSubscriptionsInternal'
type MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call struct {
	*mock.Call
}

// FetchCanceledExpiredSubscriptionsInternal is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockSubscriptionServiceInternal_Expecter) FetchCanceledExpiredSubscriptionsInternal(_a0 interface{}) *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call {
	return &MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call{Call: _e.mock.On("FetchCanceledExpiredSubscriptionsInternal", _a0)}
}

func (_c *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call) Run(run func(_a0 context.Context)) *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call) RunAndReturn(run func(context.Context) ([]*models.Subscription, error)) *MockSubscriptionServiceInternal_FetchCanceledExpiredSubscriptionsInternal_Call {
	_c.Call.Return(run)
	return _c
}

// FetchSubscriptionByIDInternal provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionServiceInternal) FetchSubscriptionByIDInternal(_a0 context.Context, _a1 bson.ObjectID) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FetchSubscriptionByIDInternal")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSubscriptionByIDInternal'
type MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call struct {
	*mock.Call
}

// FetchSubscriptionByIDInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockSubscriptionServiceInternal_Expecter) FetchSubscriptionByIDInternal(_a0 interface{}, _a1 interface{}) *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call {
	return &MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call{Call: _e.mock.On("FetchSubscriptionByIDInternal", _a0, _a1)}
}

func (_c *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*models.Subscription, error)) *MockSubscriptionServiceInternal_FetchSubscriptionByIDInternal_Call {
	_c.Call.Return(run)
	return _c
}

// FetchSubscriptionsDueForRenewalInternal provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionServiceInternal) FetchSubscriptionsDueForRenewalInternal(_a0 context.Context, _a1 time.Time, _a2 time.Time) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for FetchSubscriptionsDueForRenewalInternal")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []*models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSubscriptionsDueForRenewalInternal'
type MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call struct {
	*mock.Call
}

// FetchSubscriptionsDueForRenewalInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 time.Time
//   - _a2 time.Time
func (_e *MockSubscriptionServiceInternal_Expecter) FetchSubscriptionsDueForRenewalInternal(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call {
	return &MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call{Call: _e.mock.On("FetchSubscriptionsDueForRenewalInternal", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call) Run(run func(_a0 context.Context, _a1 time.Time, _a2 time.Time)) *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) ([]*models.Subscription, error)) *MockSubscriptionServiceInternal_FetchSubscriptionsDueForRenewalInternal_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUpcomingRenewalsInternal provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionServiceInternal) FetchUpcomingRenewalsInternal(_a0 context.Context, _a1 []int) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FetchUpcomingRenewalsInternal")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUpcomingRenewalsInternal'
type MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call struct {
	*mock.Call
}

// FetchUpcomingRenewalsInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []int
func (_e *MockSubscriptionServiceInternal_Expecter) FetchUpcomingRenewalsInternal(_a0 interface{}, _a1 interface{}) *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call {
	return &MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call{Call: _e.mock.On("FetchUpcomingRenewalsInternal", _a0, _a1)}
}

func (_c *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call) Run(run func(_a0 context.Context, _a1 []int)) *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call) RunAndReturn(run func(context.Context, []int) ([]*models.Subscription, error)) *MockSubscriptionServiceInternal_FetchUpcomingRenewalsInternal_Call {
	_c.Call.Return(run)
	return _c
}

// HasActiveSubscriptionsInternal provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionServiceInternal) HasActiveSubscriptionsInternal(_a0 context.Context, _a1 bson.ObjectID) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveSubscriptionsInternal")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActiveSubscriptionsInternal'
type MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call struct {
	*mock.Call
}

// HasActiveSubscriptionsInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockSubscriptionServiceInternal_Expecter) HasActiveSubscriptionsInternal(_a0 interface{}, _a1 interface{}) *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call {
	return &MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call{Call: _e.mock.On("HasActiveSubscriptionsInternal", _a0, _a1)}
}

func (_c *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call) Return(_a0 bool, _a1 error) *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (bool, error)) *MockSubscriptionServiceInternal_HasActiveSubscriptionsInternal_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCanceledSubscriptionAsExpiredInternal provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionServiceInternal) MarkCanceledSubscriptionAsExpiredInternal(_a0 context.Context, _a1 bson.ObjectID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MarkCanceledSubscriptionAsExpiredInternal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCanceledSubscriptionAsExpiredInternal'
type MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call struct {
	*mock.Call
}

// MarkCanceledSubscriptionAsExpiredInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockSubscriptionServiceInternal_Expecter) MarkCanceledSubscriptionAsExpiredInternal(_a0 interface{}, _a1 interface{}) *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call {
	return &MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call{Call: _e.mock.On("MarkCanceledSubscriptionAsExpiredInternal", _a0, _a1)}
}

func (_c *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call) Return(_a0 error) *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call) RunAndReturn(run func(context.Context, bson.ObjectID) error) *MockSubscriptionServiceInternal_MarkCanceledSubscriptionAsExpiredInternal_Call {
	_c.Call.Return(run)
	return _c
}

// RenewSubscriptionInternal provides a mock function with given fields: _a0, _a1
func (_m *MockSubscriptionServiceInternal) RenewSubscriptionInternal(_a0 context.Context, _a1 bson.ObjectID) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RenewSubscriptionInternal")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*models.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *models.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewSubscriptionInternal'
type MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call struct {
	*mock.Call
}

// RenewSubscriptionInternal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 bson.ObjectID
func (_e *MockSubscriptionServiceInternal_Expecter) RenewSubscriptionInternal(_a0 interface{}, _a1 interface{}) *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call {
	return &MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call{Call: _e.mock.On("RenewSubscriptionInternal", _a0, _a1)}
}

func (_c *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call) Run(run func(_a0 context.Context, _a1 bson.ObjectID)) *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.ObjectID))
	})
	return _c
}

func (_c *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call) RunAndReturn(run func(context.Context, bson.ObjectID) (*models.Subscription, error)) *MockSubscriptionServiceInternal_RenewSubscriptionInternal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionServiceInternal creates a new instance of MockSubscriptionServiceInternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionServiceInternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionServiceInternal {
	mock := &MockSubscriptionServiceInternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
