// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRateLimiterService is an autogenerated mock type for the RateLimiterService type
type MockRateLimiterService struct {
	mock.Mock
}

type MockRateLimiterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiterService) EXPECT() *MockRateLimiterService_Expecter {
	return &MockRateLimiterService_Expecter{mock: &_m.Mock}
}

// Allowed provides a mock function with given fields: ctx, ip
func (_m *MockRateLimiterService) Allowed(ctx context.Context, ip string) (int, error) {
	ret := _m.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for Allowed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, ip)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRateLimiterService_Allowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allowed'
type MockRateLimiterService_Allowed_Call struct {
	*mock.Call
}

// Allowed is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
func (_e *MockRateLimiterService_Expecter) Allowed(ctx interface{}, ip interface{}) *MockRateLimiterService_Allowed_Call {
	return &MockRateLimiterService_Allowed_Call{Call: _e.mock.On("Allowed", ctx, ip)}
}

func (_c *MockRateLimiterService_Allowed_Call) Run(run func(ctx context.Context, ip string)) *MockRateLimiterService_Allowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRateLimiterService_Allowed_Call) Return(_a0 int, _a1 error) *MockRateLimiterService_Allowed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRateLimiterService_Allowed_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRateLimiterService_Allowed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateLimiterService creates a new instance of MockRateLimiterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiterService {
	mock := &MockRateLimiterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
