// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/anuragthepathak/subscription-management/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSubscriptionServiceExternal is an autogenerated mock type for the SubscriptionServiceExternal type
type MockSubscriptionServiceExternal struct {
	mock.Mock
}

type MockSubscriptionServiceExternal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionServiceExternal) EXPECT() *MockSubscriptionServiceExternal_Expecter {
	return &MockSubscriptionServiceExternal_Expecter{mock: &_m.Mock}
}

// CancelSubscription provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionServiceExternal) CancelSubscription(_a0 context.Context, _a1 string, _a2 string) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CancelSubscription")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceExternal_CancelSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelSubscription'
type MockSubscriptionServiceExternal_CancelSubscription_Call struct {
	*mock.Call
}

// CancelSubscription is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockSubscriptionServiceExternal_Expecter) CancelSubscription(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionServiceExternal_CancelSubscription_Call {
	return &MockSubscriptionServiceExternal_CancelSubscription_Call{Call: _e.mock.On("CancelSubscription", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionServiceExternal_CancelSubscription_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockSubscriptionServiceExternal_CancelSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionServiceExternal_CancelSubscription_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionServiceExternal_CancelSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceExternal_CancelSubscription_Call) RunAndReturn(run func(context.Context, string, string) (*models.Subscription, error)) *MockSubscriptionServiceExternal_CancelSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubscription provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionServiceExternal) CreateSubscription(_a0 context.Context, _a1 *models.Subscription, _a2 string) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Subscription, string) (*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Subscription, string) *models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Subscription, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceExternal_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MockSubscriptionServiceExternal_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.Subscription
//   - _a2 string
func (_e *MockSubscriptionServiceExternal_Expecter) CreateSubscription(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionServiceExternal_CreateSubscription_Call {
	return &MockSubscriptionServiceExternal_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionServiceExternal_CreateSubscription_Call) Run(run func(_a0 context.Context, _a1 *models.Subscription, _a2 string)) *MockSubscriptionServiceExternal_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Subscription), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionServiceExternal_CreateSubscription_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionServiceExternal_CreateSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceExternal_CreateSubscription_Call) RunAndReturn(run func(context.Context, *models.Subscription, string) (*models.Subscription, error)) *MockSubscriptionServiceExternal_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionServiceExternal) DeleteSubscription(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionServiceExternal_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MockSubscriptionServiceExternal_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockSubscriptionServiceExternal_Expecter) DeleteSubscription(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionServiceExternal_DeleteSubscription_Call {
	return &MockSubscriptionServiceExternal_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionServiceExternal_DeleteSubscription_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockSubscriptionServiceExternal_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionServiceExternal_DeleteSubscription_Call) Return(_a0 error) *MockSubscriptionServiceExternal_DeleteSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionServiceExternal_DeleteSubscription_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSubscriptionServiceExternal_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSubscriptions provides a mock function with given fields: _a0
func (_m *MockSubscriptionServiceExternal) GetAllSubscriptions(_a0 context.Context) ([]*models.Subscription, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSubscriptions")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Subscription, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Subscription); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceExternal_GetAllSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSubscriptions'
type MockSubscriptionServiceExternal_GetAllSubscriptions_Call struct {
	*mock.Call
}

// GetAllSubscriptions is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockSubscriptionServiceExternal_Expecter) GetAllSubscriptions(_a0 interface{}) *MockSubscriptionServiceExternal_GetAllSubscriptions_Call {
	return &MockSubscriptionServiceExternal_GetAllSubscriptions_Call{Call: _e.mock.On("GetAllSubscriptions", _a0)}
}

func (_c *MockSubscriptionServiceExternal_GetAllSubscriptions_Call) Run(run func(_a0 context.Context)) *MockSubscriptionServiceExternal_GetAllSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSubscriptionServiceExternal_GetAllSubscriptions_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionServiceExternal_GetAllSubscriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceExternal_GetAllSubscriptions_Call) RunAndReturn(run func(context.Context) ([]*models.Subscription, error)) *MockSubscriptionServiceExternal_GetAllSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionServiceExternal) GetSubscriptionByID(_a0 context.Context, _a1 string, _a2 string) (*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByID")
	}

	var r0 *models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceExternal_GetSubscriptionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByID'
type MockSubscriptionServiceExternal_GetSubscriptionByID_Call struct {
	*mock.Call
}

// GetSubscriptionByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockSubscriptionServiceExternal_Expecter) GetSubscriptionByID(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionServiceExternal_GetSubscriptionByID_Call {
	return &MockSubscriptionServiceExternal_GetSubscriptionByID_Call{Call: _e.mock.On("GetSubscriptionByID", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionServiceExternal_GetSubscriptionByID_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockSubscriptionServiceExternal_GetSubscriptionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionServiceExternal_GetSubscriptionByID_Call) Return(_a0 *models.Subscription, _a1 error) *MockSubscriptionServiceExternal_GetSubscriptionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceExternal_GetSubscriptionByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.Subscription, error)) *MockSubscriptionServiceExternal_GetSubscriptionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsByUserID provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSubscriptionServiceExternal) GetSubscriptionsByUserID(_a0 context.Context, _a1 string, _a2 string) ([]*models.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsByUserID")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*models.Subscription, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*models.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsByUserID'
type MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call struct {
	*mock.Call
}

// GetSubscriptionsByUserID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockSubscriptionServiceExternal_Expecter) GetSubscriptionsByUserID(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call {
	return &MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call{Call: _e.mock.On("GetSubscriptionsByUserID", _a0, _a1, _a2)}
}

func (_c *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call) Return(_a0 []*models.Subscription, _a1 error) *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call) RunAndReturn(run func(context.Context, string, string) ([]*models.Subscription, error)) *MockSubscriptionServiceExternal_GetSubscriptionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionServiceExternal creates a new instance of MockSubscriptionServiceExternal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionServiceExternal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionServiceExternal {
	mock := &MockSubscriptionServiceExternal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
