// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/anuragthepathak/subscription-management/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// GenerateTokens provides a mock function with given fields: userID, email
func (_m *MockJWTService) GenerateTokens(userID string, email string) (*models.TokenResponse, error) {
	ret := _m.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokens")
	}

	var r0 *models.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.TokenResponse, error)); ok {
		return rf(userID, email)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.TokenResponse); ok {
		r0 = rf(userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_GenerateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokens'
type MockJWTService_GenerateTokens_Call struct {
	*mock.Call
}

// GenerateTokens is a helper method to define mock.On call
//   - userID string
//   - email string
func (_e *MockJWTService_Expecter) GenerateTokens(userID interface{}, email interface{}) *MockJWTService_GenerateTokens_Call {
	return &MockJWTService_GenerateTokens_Call{Call: _e.mock.On("GenerateTokens", userID, email)}
}

func (_c *MockJWTService_GenerateTokens_Call) Run(run func(userID string, email string)) *MockJWTService_GenerateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockJWTService_GenerateTokens_Call) Return(_a0 *models.TokenResponse, _a1 error) *MockJWTService_GenerateTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_GenerateTokens_Call) RunAndReturn(run func(string, string) (*models.TokenResponse, error)) *MockJWTService_GenerateTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenString, tokenType
func (_m *MockJWTService) ValidateToken(tokenString string, tokenType models.TokenType) (*models.Claims, error) {
	ret := _m.Called(tokenString, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *models.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string, models.TokenType) (*models.Claims, error)); ok {
		return rf(tokenString, tokenType)
	}
	if rf, ok := ret.Get(0).(func(string, models.TokenType) *models.Claims); ok {
		r0 = rf(tokenString, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string, models.TokenType) error); ok {
		r1 = rf(tokenString, tokenType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockJWTService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
//   - tokenType models.TokenType
func (_e *MockJWTService_Expecter) ValidateToken(tokenString interface{}, tokenType interface{}) *MockJWTService_ValidateToken_Call {
	return &MockJWTService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString, tokenType)}
}

func (_c *MockJWTService_ValidateToken_Call) Run(run func(tokenString string, tokenType models.TokenType)) *MockJWTService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.TokenType))
	})
	return _c
}

func (_c *MockJWTService_ValidateToken_Call) Return(_a0 *models.Claims, _a1 error) *MockJWTService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_ValidateToken_Call) RunAndReturn(run func(string, models.TokenType) (*models.Claims, error)) *MockJWTService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
